### ISSUE TITLE
VM execution error. Default .env

### ISSUE THREAD

**Issue by meng-x** [poanetwork/bridge-ui#179]
errors.js:29 Uncaught (in promise) Error: Returned error: VM execution error.
    at Object.ErrorResponse (http://localhost:3000/static/js/bundle.js:89731:16)
    at http://localhost:3000/static/js/bundle.js:96956:36
    at XMLHttpRequest.request.onreadystatechange (http://localhost:3000/static/js/bundle.js:112036:13)
From previous event:
    at PromiEvent (http://localhost:3000/static/js/bundle.js:96582:24)
    at send (http://localhost:3000/static/js/bundle.js:90698:21)
    at Object._executeMethod (http://localhost:3000/static/js/bundle.js:110780:24)
    at RootStore._callee$ (http://localhost:3000/static/js/bundle.js:127546:59)
    at tryCatch (http://localhost:3000/static/js/bundle.js:77465:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:77699:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:77517:21)
    at step (http://localhost:3000/static/js/bundle.js:127476:191)
    at http://localhost:3000/static/js/bundle.js:127476:437
    at new Promise (<anonymous>)
    at RootStore.<anonymous> (http://localhost:3000/static/js/bundle.js:127476:99)
    at RootStore.setBridgeMode (http://localhost:3000/static/js/bundle.js:127563:21)
    at executeAction (http://localhost:3000/static/js/bundle.js:33256:19)
    at RootStore.res (http://localhost:3000/static/js/bundle.js:33248:16)
    at new RootStore (http://localhost:3000/static/js/bundle.js:127525:10)
    at Object../src/stores/RootStore.js (http://localhost:3000/static/js/bundle.js:127574:58)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object../src/index.js (http://localhost:3000/static/js/bundle.js:124778:76)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at fn (http://localhost:3000/static/js/bundle.js:89:20)
    at Object.0 (http://localhost:3000/static/js/bundle.js:129251:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)
    at http://localhost:3000/static/js/bundle.js:725:37
    at http://localhost:3000/static/js/bundle.js:728:10
ErrorResponse @ errors.js:29
(anonymous) @ index.js:137
request.onreadystatechange @ index.js:77
Promise.then (async)
step @ HomeStore.js:383
(anonymous) @ HomeStore.js:383
(anonymous) @ HomeStore.js:383
setBridgeMode @ RootStore.js:31
executeAction @ mobx.module.js:193
res @ mobx.module.js:185
RootStore @ RootStore.js:15
./src/stores/RootStore.js @ RootStore.js:34
__webpack_require__ @ bootstrap 4a8c3985ccb47bbaf6c4:678
fn @ bootstrap 4a8c3985ccb47bbaf6c4:88
./src/index.js @ IBlockReward.json:1
__webpack_require__ @ bootstrap 4a8c3985ccb47bbaf6c4:678
fn @ bootstrap 4a8c3985ccb47bbaf6c4:88
0 @ web3.js:97
__webpack_require__ @ bootstrap 4a8c3985ccb47bbaf6c4:678
(anonymous) @ bootstrap 4a8c3985ccb47bbaf6c4:724
(anonymous) @ bootstrap 4a8c3985ccb47bbaf6c4:724
web_widget.81a9520d6bc79c9a9f55.js:8 Our embeddable contains third-party, open source software and/or libraries. To view them and their license terms, go to http://goto.zendesk.com/embeddable-legal-notices
web3.js:82 This is Kovan network. 42

**Comment by meng-x** [comment]
maybe it's about web3-providers-http, using 1.0.0-beta.30, tried 1.0.0-beta.34, error log is even less.

**Comment by patitonar** [comment]
Hi @meng-x! I was able to reproduce the error when running the app using as `.env` file the same values on `.env.example`. Is this your case?

The problem with using those default values is that the home and foreign bridge addresses are just example addresses and not real deployed bridges on the specified networks.
```
REACT_APP_HOME_BRIDGE_ADDRESS=
REACT_APP_FOREIGN_BRIDGE_ADDRESS=
REACT_APP_FOREIGN_HTTP_PARITY_URL=https://kovan.infura.io/mew
REACT_APP_HOME_HTTP_PARITY_URL=https://sokol.poa.network
```
So the error is produced because the app is making contract method calls to those addresses.

You should follow the steps on https://github.com/poanetwork/bridge-ui#getting-started to deploy and use your own bridge.

Also, If you want to take a look at already deployed bridges, you can visit:
- https://bridge.poa.network/
- https://dai-bridge.poa.network/
